name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX Document
        run: latexmk -pdf -interaction=nonstopmode -halt-on-error Lebenslauf.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: compiled_pdf
          path: ./*.pdf
